export const FETCH_SEARCH_CITY_SUCCESS = 'FETCH_SEARCH_CITY_SUCCESS';
export const FETCH_SEARCH_CITY_FAIL = 'FETCH_SEARCH_CITY_FAIL';
export const FETCH_SEARCH_CITY_LOADING  = 'FETCH_SEARCH_CITY_LOADING';
export const CLEAN_SEARCH_RESULTS ='CLEAN_SEARCH_RESULTS';

export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';
export const FETCH_WEATHER_LOADING  = 'FETCH_WEATHER_LOADING';