export const FETCH_SEARCH_CITY_SUCCESS = 'FETCH_SEARCH_CITY_SUCCESS';
export const FETCH_SEARCH_CITY_FAIL = 'FETCH_SEARCH_CITY_FAIL';
export const FETCH_SEARCH_CITY_LOADING  = 'FETCH_SEARCH_CITY_LOADING';
export const CLEAN_SEARCH_RESULTS ='CLEAN_SEARCH_RESULTS';